# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will take the code from the master branch, run the full build/test suite, and publish results to the gh-pages branch.

name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Use Node.js
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: set up git credentials
      run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" && git config --global user.name "GitHub Actions"
    - name: npm install
      run: npm install
      working-directory: ./ohmgeek

    - name: npm deploy
      run: npm run deploy
      working-directory: ./ohmgeek
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ohmgeek/build
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
